packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - prisma
  - "@prisma/client"
  - "@prisma/engines"
  - msgpackr-extract

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
