[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:next-server]
command=pnpm start
directory=/app
autorestart=true
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DATABASE_URL="postgresql://%(ENV_DB_USER)s:%(ENV_DB_PASSWORD)s@%(ENV_DB_HOST)s:%(ENV_DB_PORT)s/%(ENV_DB_NAME)s?schema=public"

[program:bullmq-worker]
command=node dist/run-worker.mjs
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DATABASE_URL="postgresql://%(ENV_DB_USER)s:%(ENV_DB_PASSWORD)s@%(ENV_DB_HOST)s:%(ENV_DB_PORT)s/%(ENV_DB_NAME)s?schema=public"
